1d_example:
  data:
    num_train: 10
    num_test: 1000
    normalize_features: false
    normalize_labels: true
  noise:
    features: 0.0
    labels_train: 0.01
    labels_test: 0.0
  vanilla_model:
    kernel: matern # matern - rbf - rff
    train:
      optimize: true
      iterations: 400
      learning_rate: 1.0e-1
      verbose: false
    save : false
    load: false
  manifold_model:
    nu: 1
    neighbors: 10
    operator: randomwalk
    method: exact
    modes: 50
    bump_scale: 5.0
    bump_decay: 0.01
    prior_bandwidth: false
    train:
      optimize: true
      iterations: 200
      learning_rate: 1.0e-1
      verbose: true
    retrain:
      optimize: false
      iterations: 200
      learning_rate: 1.0e-1
      verbose: true
    save : false
    load: false
  plot:
    save: false

2d_example:
